apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logiflow-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tanmoy095/LogiFlow-Platform
    targetRevision: main
    path: deployment/gitops/argocd/apps-dev # folder containing child apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
