#deployment/helm/services/hello/Chart.yaml
apiVersion: v2
name: hello
description: The Hello service for LogiFlow
version: 0.1.0

dependencies:
  - name: logiflow-service
    version: "0.1.0"
    repository: "file://../../library/logiflow-service"