#deployment/helm/services/llm-gateway/Chart.yaml
apiVersion: v2
name: llm-gateway
description: The llm-gateway service for LogiFlow
version: 0.1.0

dependencies:
- name: logiflow-service
  version: "0.1.0"
  repository: "file://../../library/logiflow-service"
