apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logiflow.name" . }}
  labels:
    {{- include "logiflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "logiflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "logiflow.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- include "logiflow.podSecurityContext" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          securityContext:
            {{- include "logiflow.containerSecurityContext" . | nindent 12 }}
          resources:
            {{- include "logiflow.resources" . | nindent 12 }}
          {{ include "logiflow.probes" . | nindent 10 }}
          env:
            - name: llm_gateway
              value: {{ .Chart.Name | quote }}
            - name: PORT
              value: {{ .Values.service.port | quote }}